### ISSUE TITLE
Twitter webhook is broken again

### ISSUE THREAD

**Issue by domenic** [whatwg/participate.whatwg.org#351]
Server logs say

```
[participate] [2023-07-26 12:47:03] Error: Request failed with code 401
[participate] [2023-07-26 12:47:03]     at RequestHandlerHelper.createResponseError (/app/node_modules/twitter-api-v2/dist/cjs/client-mixins/request-handler.helper.js:103:16)
[participate] [2023-07-26 12:47:03]     at RequestHandlerHelper.onResponseEndHandler (/app/node_modules/twitter-api-v2/dist/cjs/client-mixins/request-handler.helper.js:252:25)
[participate] [2023-07-26 12:47:03]     at IncomingMessage.emit (node:events:525:35)
[participate] [2023-07-26 12:47:03]     at endReadableNT (node:internal/streams/readable:1359:12)
[participate] [2023-07-26 12:47:03]     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) ApiResponseError: Request failed with code 401
[participate] [2023-07-26 12:47:03]     at RequestHandlerHelper.createResponseError (/app/node_modules/twitter-api-v2/dist/cjs/client-mixins/request-handler.helper.js:103:16)
[participate] [2023-07-26 12:47:03]     at RequestHandlerHelper.onResponseEndHandler (/app/node_modules/twitter-api-v2/dist/cjs/client-mixins/request-handler.helper.js:252:25)
[participate] [2023-07-26 12:47:03]     at IncomingMessage.emit (node:events:525:35)
[participate] [2023-07-26 12:47:03]     at endReadableNT (node:internal/streams/readable:1359:12)
[participate] [2023-07-26 12:47:03]     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
[participate] [2023-07-26 12:47:03]   error: true,
[participate] [2023-07-26 12:47:03]   type: 'response',
[participate] [2023-07-26 12:47:03]   code: 401,
[participate] [2023-07-26 12:47:03]   headers: {
[participate] [2023-07-26 12:47:03]     perf: '7626143928',
[participate] [2023-07-26 12:47:03]     'content-type': 'application/problem+json',
[participate] [2023-07-26 12:47:03]     'cache-control': 'no-cache, no-store, max-age=0',
[participate] [2023-07-26 12:47:03]     'content-length': '99',
[participate] [2023-07-26 12:47:03]     'x-transaction-id': 'e1d25a511ed69c7f',
[participate] [2023-07-26 12:47:03]     'x-response-time': '4',
[participate] [2023-07-26 12:47:03]     'x-connection-hash': '66e8051a666d6f29f78733a42b341f6291adda1f0e97054487638530d6b1f583',
[participate] [2023-07-26 12:47:03]     date: 'Wed, 26 Jul 2023 12:47:03 GMT',
[participate] [2023-07-26 12:47:03]     server: 'tsa_b',
[participate] [2023-07-26 12:47:03]     connection: 'close'
[participate] [2023-07-26 12:47:03]   },
[participate] [2023-07-26 12:47:03]   rateLimit: undefined,
[participate] [2023-07-26 12:47:03]   data: {
[participate] [2023-07-26 12:47:03]     title: 'Unauthorized',
[participate] [2023-07-26 12:47:03]     type: 'about:blank',
[participate] [2023-07-26 12:47:03]     status: 401,
[participate] [2023-07-26 12:47:03]     detail: 'Unauthorized'
[participate] [2023-07-26 12:47:03]   }
[participate] [2023-07-26 12:47:03] }
```

Not so optimistic this time about fixing it; we'll see.

**Comment by domenic** [comment]
I guess the whattweetbot account got deleted. No emails I can find about why.

I guess we can recreate the app under the `@WHATWG` account, which is more of a true legitimate account? Not sure; that's a bit risky. It wouldn't be much work though. And if they shut down `@WHATWG`, then we just quit Twitter?

**Comment by annevk** [comment]
I thought it was created under that account? But also not interested in investing time in such an unstable platform.
